### ISSUE TITLE
Is the API maintained at all? Getting 500 on example

### ISSUE THREAD

**Issue by RobinJayaswal** [infogram/infogram-node#8] opened 2018-05-29 23:21 UTC
Running the simple example found here: https://github.com/infogram/infogram-node/blob/master/examples/examples.js

Getting a nondescript 500. Is the API still maintained?

**Comment by martinsb** [comment] 2018-05-30 10:54
Hello @RobinJayaswal,
Thank you for reporting the issue. The problem is fixed now.

**Closed as completed by martinsb** 2018-05-30 10:54 UTC
